# Generated by Django 5.1.4 on 2025-01-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_address_is_default'),
        ('user', '0003_auto_20250125_1527'),
    ]

    operations = [
    ]
